name: flutter_carrot_market_d5354
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

# svg : 벡터 형식 이미지(크기가 바뀌어도 해상도가 떨어지지 않음)
# intl : 단위 변환용(원)
# carousel_slider : 다양한 슬라이더 제공
# flutter_secure_storage : 로컬 스토리지에 접근
dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: # 이미지 관련 폴더 추가
    - assets/svg/
    - assets/images/
